name: "test"

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - run: bun run .output/server/index.mjs
